language: java
deploy:
  provider: heroku
  api_key:
    secure: kG5UsAFn/dKOMJTRXIgTk8j0W4ONhv6k8m/0vBfToRj/KYHYlTrsBBGD9SfLXjhJO+MP4ZbHDlkcW0ukerXdQTN4Fl/NtlI1/sYdUiXBS2ZDdgSFJvGkNGTVD6N/G/kvoeVwhG+pPvCfIna5NRQB70aqkiaannnVauKlUR8UlsROnpH44E06CQBIH31TNH7/M29FzrzNpq41cvj2resSxTJVLqZuAG73IpVXk3zc/iERnIhTlRF8v6NtaTqU2E82/zazRbKmkuRVtRB3XPRu/dZdUFg40DOv4a3Gad7Y1UB01I7Lfo74HzWnux+vj1BZtTnWkD/J2AYxfsHrcJK9ZxixZlE2sVMlky2mF1PHz8Aj76Y/Pak2a+sbbLIzHWz2ctoKA9sbRa1vo3aOGVJb9uCoblasZanDahrCqG4X3/vDFbZC8YW5IG/ClwEN4rAM4nY11pZSbXp9eju/npDHxKUXwznKtxRRwNGeJ2XXfFW69owowIc0D+9HhTo0RvWmZ+ozl6z8e0f9xa5eEn5PZZqiUbOdDwHksTYDKYnc/xidnrwz9e1Tu5AzgiDh6Kb2FdUjqI9ccijFIVFpM3bjKLftaHScskWtCJIwgVR6/5MmSXDZWdDOKqXpWH+Fy0X+o/MsH3s/V6BnRb3Axucu5UGAIMk9nXVQAs078rHjowk=
  app: stark-depths-10850
